dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.1"
dotenv: .env
networks:
  default: development
  goerli:
    verify: True

wallets:
  from_key: ${PRIVATE_KEY}
